version: '3.3'
services:
  test:
    container_name: '${POSTGRES_CONTAINER}'
    image: postgres:12.1-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: '${POSTGRES_USER}'
    volumes:
      - /Volumes/github-issue-viewer-test:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      default:
        aliases:
          - postgres.service.test
